from .tutor_prompt import TUTOR_SYSTEM_PROMPT, TUTOR_QUERY_TEMPLATE
from .planner_prompt import PLANNER_SYSTEM_PROMPT, PLANNER_TEMPLATE
from .quiz_prompt import QUIZ_SYSTEM_PROMPT, QUIZ_TEMPLATE

__all__ = [
    "TUTOR_SYSTEM_PROMPT",
    "TUTOR_QUERY_TEMPLATE",
    "PLANNER_SYSTEM_PROMPT",
    "PLANNER_TEMPLATE",
    "QUIZ_SYSTEM_PROMPT",
    "QUIZ_TEMPLATE"
]
